version: '3.7'

services:
  car-insurance-app:
    container_name: car-insurance-app
    build:
      context: car-insurance-app
      dockerfile: Dockerfile
    ports:
      - '4200:4200'

  car-insurance-services:
    container_name: car-insurance-services
    build:
      context: car-insurance-services
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    #networks:
    #  - frontend
  
  # Database Service (Mysql)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: car_insurance
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
#networks:
#  frontend: